create O:\arm7\tests\02-platform\007_simple_flat_boot_handoff\disk0-test.img 1M
format O:\arm7\tests\02-platform\007_simple_flat_boot_handoff\disk0-test.img
put O:\arm7\tests\02-platform\007_simple_flat_boot_handoff\disk0-test.img O:\arm7\tests\02-platform\007_simple_flat_boot_handoff\DUMMY.BIN DUMMY.BIN
put O:\arm7\tests\02-platform\007_simple_flat_boot_handoff\disk0-test.img O:\arm7\tests\02-platform\007_simple_flat_boot_handoff\BOOT.BIN BOOT.BIN
list O:\arm7\tests\02-platform\007_simple_flat_boot_handoff\disk0-test.img
