create O:\arm7\tests\02-platform\008_simple_flat_find_monitor\disk0-test.img 1M
format O:\arm7\tests\02-platform\008_simple_flat_find_monitor\disk0-test.img
put O:\arm7\tests\02-platform\008_simple_flat_find_monitor\disk0-test.img O:\arm7\tests\02-platform\008_simple_flat_find_monitor\DUMMY.BIN DUMMY.BIN
put O:\arm7\tests\02-platform\008_simple_flat_find_monitor\disk0-test.img O:\arm7\tests\02-platform\008_simple_flat_find_monitor\BOOT.BIN BOOT.BIN
put O:\arm7\tests\02-platform\008_simple_flat_find_monitor\disk0-test.img O:\arm7\tests\02-platform\008_simple_flat_find_monitor\MONITOR.BIN MONITOR.BIN
info O:\arm7\tests\02-platform\008_simple_flat_find_monitor\disk0-test.img
list O:\arm7\tests\02-platform\008_simple_flat_find_monitor\disk0-test.img
