#!/usr/bin/env python3
import sys
from pathlib import Path

def main():
    if len(sys.argv) != 3:
        print("usage: embed_bios.py <bios.bin> <default_bios.h>", file=sys.stderr)
        return 2

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    data = src.read_bytes()

    rows = []
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")

    text = f"""/* AUTO-GENERATED. DO NOT EDIT.
 *
 * Source: {src.as_posix()}
 * Generated by embed_bios.py
 */
#ifndef ARM7_DEFAULT_BIOS_H
#define ARM7_DEFAULT_BIOS_H

#include <stddef.h>
#include <stdint.h>

static const uint8_t default_bios[] = {{
{chr(10).join(rows)}
}};

static const size_t default_bios_size = sizeof(default_bios);

#endif
"""
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(text, encoding="utf-8", newline="\n")
    print(f"Embedded {len(data)} BIOS bytes -> {dst}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
