#!/usr/bin/env python3
import sys
from pathlib import Path

def main():
    if len(sys.argv) != 3:
        print("usage: embed_bios.py <bios.bin> <default_bios.h>", file=sys.stderr)
        return 2

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    data = src.read_bytes()

    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")

    text = """/* AUTO-GENERATED. DO NOT EDIT.
 *
 * Source: firmware/bios/bios.bin
 * Generated by vm/arm7-runx/tools/embed_bios.py
 */
#ifndef ARM7_RUNX_DEFAULT_BIOS_H
#define ARM7_RUNX_DEFAULT_BIOS_H

#include <stddef.h>
#include <stdint.h>

static const uint8_t default_bios[] = {
%s
};

static const size_t default_bios_size = sizeof(default_bios);

#endif
""" % "\\n".join(lines)

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(text, encoding="utf-8", newline="\\n")
    print(f"Embedded {len(data)} BIOS bytes -> {dst}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
